<?php if ($this->pageCount) : ?>
    <nav aria-label="...">
        <ul class="pagination">
            <?php if ($this->previous) : ?>
                <li class="page-item">
                    <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]); ?>" class="page-link">Previous</a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current): ?>
                    <li class="page-item">
                        <a href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]); ?>" class="page-link"><?= $page ?></a>
                    </li>
                <?php else: ?>
                    <li class="page-item active" aria-current="page">
                        <a href="#" class="page-link"><?= $page ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)) : ?>
                <li class="page-item">
                    <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]); ?>" class="page-link">Next</a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>