<?php

$title = $this->translate('Sign Up');

$this->headTitle($this->escapeHtml($title));
$this->headMeta()->appendName('keywords', 'Sign Up, New Account');
$this->headMeta()->appendName('description', 'Create a new account');

$form = $this->form;
$form->setAttribute('action', $this->url('signup'));
$form->prepare();

?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2><?= $this->escapeHtml($title) ?></h2>

            <?= $this->form()->openTag($form) ?>

            <span class="form-text text-muted pb-2">
                <?= sprintf($this->translate('Already have an account? %sLogin here%s'), '<a href="'. $this->url('login') .'">', '</a>') ?>
            </span>

            <div class="mb-3">
                <?= $this->formLabel($form->get('username')) ?>
                <div class="form-group">
                    <?= $this->formText($form->get('username')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('username')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('gender')) ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('gender')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('gender')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('email')) ?>
                <div class="form-group">
                    <?= $this->formEmail($form->get('email')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('email')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('confirm_email')) ?>
                <div class="form-group">
                    <?= $this->formEmail($form->get('confirm_email')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('confirm_email')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('birthday')) ?>
                <div class="form-group">
                    <?= $this->formDateSelect($form->get('birthday')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('birthday')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('password')) ?>
                <div class="form-group">
                    <?= $this->formPassword($form->get('password')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('password')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('confirm_password')) ?>
                <div class="form-group">
                    <?= $this->formPassword($form->get('confirm_password')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('confirm_password')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('csrf')) ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')) ?>
                </div>

                <?= $this->formSubmit($form->get('create_account')) ?>
            </div>

            <?= $this->form()->closeTag() ?>
            
        </div>
        <div class="col-md-6"></div>
    </div>
</div>