<?php

$title = $this->translate('Forgot Password');

$this->headTitle($this->escapeHtml($title));
$this->headMeta()->appendName('keywords', 'Forgot Password, Password Reset');
$this->headMeta()->appendName('description', 'I forgot my password');

$form = $this->form;
$form->setAttribute('action', $this->url('forgot_password'));
$form->prepare();

?>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2><?= $this->escapeHtml($title) ?></h2>

            <?= $this->form()->openTag($form) ?>

            <span class="form-text text-muted pb-2">
                <?= $this->translate('Provide the email address associated with your account.') ?>
            </span>

            <div class="mb-3">
                <?= $this->formLabel($form->get('email')) ?>
                <div class="form-group">
                    <?= $this->formEmail($form->get('email')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('email')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('captcha')) ?>
                <div class="form-group">
                    <?= $this->formCaptcha($form->get('captcha')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('captcha')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('csrf')) ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')) ?>
                </div>

                <?= $this->formSubmit($form->get('forgot_password')) ?>
            </div>

            <?= $this->form()->closeTag() ?>
            
        </div>
        <div class="col-md-8"></div>
    </div>
</div>