<?php

$title = $this->translate('Sign In');

$this->headTitle($this->escapeHtml($title));
$this->headMeta()->appendName('keywords', 'Sign In, Login');
$this->headMeta()->appendName('description', 'Login to my account');

$form = $this->form;
$form->setAttribute('action', $this->url('login'));
$form->prepare();

?>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2><?= $this->escapeHtml($title) ?></h2>

            <?= $this->form()->openTag($form) ?>

            <span class="form-text text-muted pb-2">
                <?= sprintf($this->translate('Don\'t have an account yet? %sJoin here%s'), '<a href="'. $this->url('signup') .'">', '</a>') ?>
            </span>

            <div class="mb-3">
                <?= $this->formLabel($form->get('email')) ?>
                <div class="form-group">
                    <?= $this->formEmail($form->get('email')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('email')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('password')) ?>
                <div class="form-group">
                    <?= $this->formPassword($form->get('password')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('password')) ?>
                </div>
            </div>

            <div class="mb-3">
                <div class="custom-control custom-checkbox">
                <?= $this->formCheckbox($form->get('recall')) ?>
                <?= $this->formLabel($form->get('recall')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('csrf')) ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')) ?>
                </div>

                <?= $this->formSubmit($form->get('sign_in')) ?>
            </div>

            <?= sprintf($this->translate('%sForgot Password?%s'), '<a href="'. $this->url('forgot_password') .'">', '</a>') ?>

            <?= $this->form()->closeTag() ?>
            
        </div>
        <div class="col-md-8"></div>
    </div>
</div>