<div class="container">
    <h2>Settings</h2>
    <ul>
        <li><a href="<?= $this->url('settings', ['action' => 'email']) ?>">Change e-mail address</a></li>
        <li><a href="<?= $this->url('settings', ['action' => 'password']) ?>">Change password</a></li>
        <li><a href="<?= $this->url('settings', ['action' => 'username']) ?>">Change username</a></li>
        <li><a href="<?= $this->url('settings', ['action' => 'delete']) ?>">Delete account</a></li>
    </ul>
</div>