<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas Quiz')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript()->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton
                    </a>
                </div>
                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">
                                Home
                            </a>
                        </li>
                        <?php if (!$this->identity()): ?>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('login') ?>">
                                    Login
                                </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('signup') ?>">
                                    Sign Up
                                </a>
                            </li>
                        <?php else: ?>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('quiz', ['action' => 'index']) ?>">
                                    Quizzes
                                </a>
                            </li>
                            <?php if ($this->identity()->role_id == 1): ?>
                                <li class="nav-item active">
                                    <a class="nav-link" href="<?= $this->url('admin_user', ['action' => 'index']) ?>">
                                        Admin
                                    </a>
                                </li>
                            <?php endif ?>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'index']) ?>">
                                    Settings
                                </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('logout') ?>">
                                    Logout
                                </a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->partial('partial/flash.phtml', $this->flashMessenger()) ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <div class="float-left mb-3">
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC. 
                </div>
                <div class="float-right mb-3">
                    <a href="<?= $this->url('help', ['action' => 'contact']) ?>">Contact</a> | 
                    <a href="<?= $this->url('help', ['action' => 'privacy']) ?>">Privacy</a> | 
                    <a href="<?= $this->url('help', ['action' => 'terms']) ?>">Terms</a>
                </div>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.timeago.js')) ?>
    </body>
</html>
