<?php

$title = $this->translate('New Quiz');

$this->headTitle($this->escapeHtml($title));
$this->headMeta()->appendName('keywords', 'Quiz');
$this->headMeta()->appendName('description', 'Create a new quiz');

$form = $this->form;
$form->setAttribute('action', $this->url('quiz', ['action' => 'create']));
$form->prepare();

?>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2><?= $this->escapeHtml($title) ?></h2>

            <?= $this->form()->openTag($form) ?>

            <div class="mb-3">
                <?= $this->formLabel($form->get('category_id')) ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('category_id')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('category_id')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('timeout')) ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('timeout')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('timeout')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('title')) ?>
                <div class="form-group">
                    <?= $this->formText($form->get('title')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('title')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('question')) ?>
                <div class="form-group">
                    <?= $this->formTextArea($form->get('question')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('question')) ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('answers[]')) ?>
                <div class="form-group">
                    <?= $this->formText($form->get('answers[]')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('answers[]')) ?>
                </div>
            </div>

            <div class="mb-3">
                <div class="form-group">
                    <?= $this->formText($form->get('answers[]')) ?>
                </div>

                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('answers[]')) ?>
                </div>
            </div>

            <div id="wrapper"></div>

            <div class="mb-3">
                <?= $this->formButton($form->get('add_more')) ?>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('user_id')->setValue($this->authHelper()->getId())) ?>
                <?= $this->formHidden($form->get('csrf')) ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')) ?>
                </div>

                <?= $this->formSubmit($form->get('create_quiz')) ?>
            </div>

            <?= $this->form()->closeTag() ?>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

<script type="text/javascript">
$(function() {
    let minFields = 3;
    let maxFields = 5;
    let inputField = `<div class="mb-3">
        <div class="input-group">
            <input type="text" name="answers[]" class="form-control">
            <div class="input-group-append delete">
                <span class="input-group-text">&times;</span>
            </div>
        </div>
    </div>`;

    $(document).on('click', '#add_more', function() {
        $('#wrapper').append(inputField);
        minFields++;
        if (minFields > maxFields) {
            $('#add_more').hide();
        }
    });

    $(document).on('click', '.delete', function() {
        $(this).parent().parent().remove();
        minFields--;
        if (minFields <= maxFields) {
            $('#add_more').show();
        }
    });
});
</script>

